#!/bin/sh
case "$1" in
    start)
        echo "Starting aesd_bme280 module"
        module_load aesd_bme280
        ;;
    stop)
        echo "Stopping aesd_bme280 module"
        module_unload aesd_bme280
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac