#!/bin/sh
case "$1" in
    start)
        echo "Starting MQTT broker and daemons"
        mqtt_publisher
        mqtt_subscriber
        ;;
    stop)
        echo "Stopping MQTT broker and daemons"
        killall mqtt_publisher
        killall mqtt_subscriber
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac